/* !!!
 * This file was auto-generated by schema-gen
 * Do not edit this file manually.
 * !!!
 */

package com.unazed.LibraryManagement;

import com.unazed.LibraryManagement.SqlInterface;
import com.unazed.LibraryManagement.model.gen.ResultType;
import com.unazed.LibraryManagement.model.gen.UserStatus;
import java.sql.*;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;

public class DatabaseFunctions 
{
	private static final Logger logger = Logger.getLogger(DatabaseFunctions.class.getName());
	private static final SqlInterface sqlInterface = SqlInterface.get();

	private static final Connection conn = sqlInterface.getConnection();

	public static ResultType registerUser(
		String pEmail, String pUsername, String pPassword
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_api.register_user(?, ?, ?)"))
		{
			stmt.setObject(1, pEmail);
			stmt.setObject(2, pUsername);
			stmt.setObject(3, pPassword);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'register_user'");
			return ResultType.fromResultSet(rs);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'register_user'", sqlExc);
			throw sqlExc;
		}
	}

	public static ResultType loginUser(
		String pEmail, String pPassword
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_api.login_user(?, ?)"))
		{
			stmt.setObject(1, pEmail);
			stmt.setObject(2, pPassword);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'login_user'");
			return ResultType.fromResultSet(rs);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'login_user'", sqlExc);
			throw sqlExc;
		}
	}

	public static ResultType addBook(
		String pToken, String pIsbn, String pName, LocalDate pPublishDate, Integer pQuantity, boolean pHasDigital
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_api.add_book(?, ?, ?, ?, ?, ?)"))
		{
			stmt.setObject(1, pToken);
			stmt.setObject(2, pIsbn);
			stmt.setObject(3, pName);
			stmt.setObject(4, pPublishDate);
			stmt.setObject(5, pQuantity);
			stmt.setObject(6, pHasDigital);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'add_book'");
			return ResultType.fromResultSet(rs);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'add_book'", sqlExc);
			throw sqlExc;
		}
	}

	public static ResultType findBookByIsbn(
		String pIsbn
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_api.find_book_by_isbn(?)"))
		{
			stmt.setObject(1, pIsbn);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'find_book_by_isbn'");
			return ResultType.fromResultSet(rs);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'find_book_by_isbn'", sqlExc);
			throw sqlExc;
		}
	}

	public static ResultType setDigitalBookUrl(
		String pToken, String pIsbn, String pUrl
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_api.set_digital_book_url(?, ?, ?)"))
		{
			stmt.setObject(1, pToken);
			stmt.setObject(2, pIsbn);
			stmt.setObject(3, pUrl);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'set_digital_book_url'");
			return ResultType.fromResultSet(rs);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'set_digital_book_url'", sqlExc);
			throw sqlExc;
		}
	}

	public static ResultType updateBook(
		String pToken, String pIsbn, String pName, LocalDate pPublishDate, Integer pQuantity, boolean pHasDigital
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_api.update_book(?, ?, ?, ?, ?, ?)"))
		{
			stmt.setObject(1, pToken);
			stmt.setObject(2, pIsbn);
			stmt.setObject(3, pName);
			stmt.setObject(4, pPublishDate);
			stmt.setObject(5, pQuantity);
			stmt.setObject(6, pHasDigital);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'update_book'");
			return ResultType.fromResultSet(rs);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'update_book'", sqlExc);
			throw sqlExc;
		}
	}

	public static ResultType removeBook(
		String pToken, String pIsbn
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_api.remove_book(?, ?)"))
		{
			stmt.setObject(1, pToken);
			stmt.setObject(2, pIsbn);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'remove_book'");
			return ResultType.fromResultSet(rs);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'remove_book'", sqlExc);
			throw sqlExc;
		}
	}

	public static ResultType getQtyPhysicalAvailable(
		String pToken, String pIsbn, OffsetDateTime pFrom, OffsetDateTime pTo
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_api.get_qty_physical_available(?, ?, ?, ?)"))
		{
			stmt.setObject(1, pToken);
			stmt.setObject(2, pIsbn);
			stmt.setObject(3, pFrom);
			stmt.setObject(4, pTo);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'get_qty_physical_available'");
			return ResultType.fromResultSet(rs);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'get_qty_physical_available'", sqlExc);
			throw sqlExc;
		}
	}

	public static ResultType createPhysicalLoan(
		String pToken, String pIsbn, Integer pLoaneeId, OffsetDateTime pFromDate, OffsetDateTime pToDate, Integer pQuantity
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_api.create_physical_loan(?, ?, ?, ?, ?, ?)"))
		{
			stmt.setObject(1, pToken);
			stmt.setObject(2, pIsbn);
			stmt.setObject(3, pLoaneeId);
			stmt.setObject(4, pFromDate);
			stmt.setObject(5, pToDate);
			stmt.setObject(6, pQuantity);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'create_physical_loan'");
			return ResultType.fromResultSet(rs);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'create_physical_loan'", sqlExc);
			throw sqlExc;
		}
	}

	public static ResultType getPhysicalLoans(
		String pToken, String pIsbn
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_api.get_physical_loans(?, ?)"))
		{
			stmt.setObject(1, pToken);
			stmt.setObject(2, pIsbn);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'get_physical_loans'");
			return ResultType.fromResultSet(rs);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'get_physical_loans'", sqlExc);
			throw sqlExc;
		}
	}

	public static ResultType getPhysicalLoanById(
		String pToken, Integer pLoanId
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_api.get_physical_loan_by_id(?, ?)"))
		{
			stmt.setObject(1, pToken);
			stmt.setObject(2, pLoanId);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'get_physical_loan_by_id'");
			return ResultType.fromResultSet(rs);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'get_physical_loan_by_id'", sqlExc);
			throw sqlExc;
		}
	}

	public static ResultType getDigitalLoans(
		String pToken, String pIsbn
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_api.get_digital_loans(?, ?)"))
		{
			stmt.setObject(1, pToken);
			stmt.setObject(2, pIsbn);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'get_digital_loans'");
			return ResultType.fromResultSet(rs);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'get_digital_loans'", sqlExc);
			throw sqlExc;
		}
	}

	public static ResultType updatePhysicalLoan(
		String pToken, Integer pLoanId, OffsetDateTime pLoanDate, OffsetDateTime pLoanReturnDate, boolean pLoanReturned
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_api.update_physical_loan(?, ?, ?, ?, ?)"))
		{
			stmt.setObject(1, pToken);
			stmt.setObject(2, pLoanId);
			stmt.setObject(3, pLoanDate);
			stmt.setObject(4, pLoanReturnDate);
			stmt.setObject(5, pLoanReturned);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'update_physical_loan'");
			return ResultType.fromResultSet(rs);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'update_physical_loan'", sqlExc);
			throw sqlExc;
		}
	}

	public static ResultType removePhysicalLoan(
		String pToken, Integer pLoanId
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_api.remove_physical_loan(?, ?)"))
		{
			stmt.setObject(1, pToken);
			stmt.setObject(2, pLoanId);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'remove_physical_loan'");
			return ResultType.fromResultSet(rs);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'remove_physical_loan'", sqlExc);
			throw sqlExc;
		}
	}

	public static ResultType removeDigitalLoan(
		String pToken, Integer pLoanId
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_api.remove_digital_loan(?, ?)"))
		{
			stmt.setObject(1, pToken);
			stmt.setObject(2, pLoanId);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'remove_digital_loan'");
			return ResultType.fromResultSet(rs);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'remove_digital_loan'", sqlExc);
			throw sqlExc;
		}
	}

	public static ResultType getMembers(
		String pToken
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_api.get_members(?)"))
		{
			stmt.setObject(1, pToken);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'get_members'");
			return ResultType.fromResultSet(rs);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'get_members'", sqlExc);
			throw sqlExc;
		}
	}

	public static ResultType getTokenInformation(
		String pToken
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_api.get_token_information(?)"))
		{
			stmt.setObject(1, pToken);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'get_token_information'");
			return ResultType.fromResultSet(rs);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'get_token_information'", sqlExc);
			throw sqlExc;
		}
	}

	public static ResultType updateUserDetails(
		String pToken, Integer pUserId, String pEmail, String pUsername, UserStatus pAccountStatus
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_api.update_user_details(?, ?, ?, ?, ?)"))
		{
			stmt.setObject(1, pToken);
			stmt.setObject(2, pUserId);
			stmt.setObject(3, pEmail);
			stmt.setObject(4, pUsername);
			stmt.setObject(5, pAccountStatus.value(), Types.OTHER);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'update_user_details'");
			return ResultType.fromResultSet(rs);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'update_user_details'", sqlExc);
			throw sqlExc;
		}
	}

	public static ResultType getAuthors(
		String pToken
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_api.get_authors(?)"))
		{
			stmt.setObject(1, pToken);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'get_authors'");
			return ResultType.fromResultSet(rs);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'get_authors'", sqlExc);
			throw sqlExc;
		}
	}

	public static ResultType addAuthor(
		String pToken, String pIsbn, String pFirstName, String pLastName, Integer pAuthorId
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_api.add_author(?, ?, ?, ?, ?)"))
		{
			stmt.setObject(1, pToken);
			stmt.setObject(2, pIsbn);
			stmt.setObject(3, pFirstName);
			stmt.setObject(4, pLastName);
			stmt.setObject(5, pAuthorId);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'add_author'");
			return ResultType.fromResultSet(rs);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'add_author'", sqlExc);
			throw sqlExc;
		}
	}

}
