/* !!!
 * This file was auto-generated by schema-gen
 * Do not edit this file manually.
 * !!!
 */

package com.unazed.LibraryManagement;

import com.google.gson.JsonElement;
import com.unazed.LibraryManagement.SqlInterface;
import com.unazed.LibraryManagement.model.gen.ResultType;
import java.sql.*;
import java.time.OffsetDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;

public class DatabaseInternalFunctions 
{
	private static final Logger logger = Logger.getLogger(DatabaseInternalFunctions.class.getName());
	private static final SqlInterface sqlInterface = SqlInterface.get();

	private static final Connection conn = sqlInterface.getConnection();

	public static ResultType makeSuccessResult(
		Object data
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_internal.make_success_result(?)"))
		{
			stmt.setObject(1, data);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'make_success_result'");
			return ResultType.fromResultSet(rs);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'make_success_result'", sqlExc);
			throw sqlExc;
		}
	}

	public static ResultType makeErrorResult(
		Object errorCode
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_internal.make_error_result(?)"))
		{
			stmt.setObject(1, errorCode);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'make_error_result'");
			return ResultType.fromResultSet(rs);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'make_error_result'", sqlExc);
			throw sqlExc;
		}
	}

	public static String getUserRole(
		Integer pUserId
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_internal.get_user_role(?)"))
		{
			stmt.setObject(1, pUserId);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'get_user_role'");
			return (String) rs.getObject(1);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'get_user_role'", sqlExc);
			throw sqlExc;
		}
	}

	public static String normalizeEmail(
		String email
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_internal.normalize_email(?)"))
		{
			stmt.setObject(1, email);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'normalize_email'");
			return (String) rs.getObject(1);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'normalize_email'", sqlExc);
			throw sqlExc;
		}
	}

	public static String getAppConfigValue(
		String pKey
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_internal.get_app_config_value(?)"))
		{
			stmt.setObject(1, pKey);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'get_app_config_value'");
			return (String) rs.getObject(1);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'get_app_config_value'", sqlExc);
			throw sqlExc;
		}
	}

	public static JsonElement decodeToken(
		String pToken
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_internal.decode_token(?)"))
		{
			stmt.setObject(1, pToken);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'decode_token'");
			return (JsonElement) rs.getObject(1);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'decode_token'", sqlExc);
			throw sqlExc;
		}
	}

	public static boolean existsUser(
		Integer pUserId
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_internal.exists_user(?)"))
		{
			stmt.setObject(1, pUserId);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'exists_user'");
			return (boolean) rs.getObject(1);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'exists_user'", sqlExc);
			throw sqlExc;
		}
	}

	public static ResultType isValidSession(
		String pToken
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_internal.is_valid_session(?)"))
		{
			stmt.setObject(1, pToken);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'is_valid_session'");
			return ResultType.fromResultSet(rs);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'is_valid_session'", sqlExc);
			throw sqlExc;
		}
	}

	public static ResultType isLibrarian(
		String pToken
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_internal.is_librarian(?)"))
		{
			stmt.setObject(1, pToken);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'is_librarian'");
			return ResultType.fromResultSet(rs);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'is_librarian'", sqlExc);
			throw sqlExc;
		}
	}

	public static boolean existsBookByIsbn(
		String pIsbn
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_internal.exists_book_by_isbn(?)"))
		{
			stmt.setObject(1, pIsbn);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'exists_book_by_isbn'");
			return (boolean) rs.getObject(1);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'exists_book_by_isbn'", sqlExc);
			throw sqlExc;
		}
	}

	public static Integer getMaxConcurrentPhysicalLoans(
		String pIsbn, OffsetDateTime pFrom, OffsetDateTime pTo
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_internal.get_max_concurrent_physical_loans(?, ?, ?)"))
		{
			stmt.setObject(1, pIsbn);
			stmt.setObject(2, pFrom);
			stmt.setObject(3, pTo);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'get_max_concurrent_physical_loans'");
			return (Integer) rs.getObject(1);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'get_max_concurrent_physical_loans'", sqlExc);
			throw sqlExc;
		}
	}

	public static Integer getQtyPhysicalLoans(
		String pIsbn
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_internal.get_qty_physical_loans(?)"))
		{
			stmt.setObject(1, pIsbn);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'get_qty_physical_loans'");
			return (Integer) rs.getObject(1);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'get_qty_physical_loans'", sqlExc);
			throw sqlExc;
		}
	}

	public static boolean isActivePhysicalLoan(
		Integer pLoanId
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_internal.is_active_physical_loan(?)"))
		{
			stmt.setObject(1, pLoanId);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'is_active_physical_loan'");
			return (boolean) rs.getObject(1);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'is_active_physical_loan'", sqlExc);
			throw sqlExc;
		}
	}

	public static boolean isActiveDigitalLoan(
		Integer pLoanId
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_internal.is_active_digital_loan(?)"))
		{
			stmt.setObject(1, pLoanId);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'is_active_digital_loan'");
			return (boolean) rs.getObject(1);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'is_active_digital_loan'", sqlExc);
			throw sqlExc;
		}
	}

	public static boolean hasActivePhysicalLoans(
		String pIsbn
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_internal.has_active_physical_loans(?)"))
		{
			stmt.setObject(1, pIsbn);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'has_active_physical_loans'");
			return (boolean) rs.getObject(1);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'has_active_physical_loans'", sqlExc);
			throw sqlExc;
		}
	}

	public static boolean hasActiveDigitalLoans(
		String pIsbn
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_internal.has_active_digital_loans(?)"))
		{
			stmt.setObject(1, pIsbn);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'has_active_digital_loans'");
			return (boolean) rs.getObject(1);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'has_active_digital_loans'", sqlExc);
			throw sqlExc;
		}
	}

	public static Integer getQtyDigitalLoans(
		String pIsbn
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_internal.get_qty_digital_loans(?)"))
		{
			stmt.setObject(1, pIsbn);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'get_qty_digital_loans'");
			return (Integer) rs.getObject(1);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'get_qty_digital_loans'", sqlExc);
			throw sqlExc;
		}
	}

	public static boolean isPhysicalBook(
		String pIsbn
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_internal.is_physical_book(?)"))
		{
			stmt.setObject(1, pIsbn);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'is_physical_book'");
			return (boolean) rs.getObject(1);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'is_physical_book'", sqlExc);
			throw sqlExc;
		}
	}

	public static boolean existsAuthorById(
		Integer pAuthorId
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_internal.exists_author_by_id(?)"))
		{
			stmt.setObject(1, pAuthorId);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'exists_author_by_id'");
			return (boolean) rs.getObject(1);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'exists_author_by_id'", sqlExc);
			throw sqlExc;
		}
	}

	public static boolean userHasPhysicalLoan(
		Integer pUserId, String pIsbn, OffsetDateTime pFromDate, OffsetDateTime pToDate
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_internal.user_has_physical_loan(?, ?, ?, ?)"))
		{
			stmt.setObject(1, pUserId);
			stmt.setObject(2, pIsbn);
			stmt.setObject(3, pFromDate);
			stmt.setObject(4, pToDate);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'user_has_physical_loan'");
			return (boolean) rs.getObject(1);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'user_has_physical_loan'", sqlExc);
			throw sqlExc;
		}
	}

	public static ResultType getQtyPhysicalAvailable(
		String pIsbn, OffsetDateTime pFrom, OffsetDateTime pTo
	) throws SQLException
	{
		try (PreparedStatement stmt = conn.prepareStatement(
			"SELECT * from library_internal.get_qty_physical_available(?, ?, ?)"))
		{
			stmt.setObject(1, pIsbn);
			stmt.setObject(2, pFrom);
			stmt.setObject(3, pTo);
			ResultSet rs = stmt.executeQuery();
			if (!rs.next())
				throw new SQLException("No result returned from function 'get_qty_physical_available'");
			return ResultType.fromResultSet(rs);
		} catch (SQLException sqlExc)
		{
			logger.log(Level.SEVERE, "Error executing function 'get_qty_physical_available'", sqlExc);
			throw sqlExc;
		}
	}

}
