/* !!!
 * This file was auto-generated by schema-gen/main.py
 * Do not edit this file manually.
 * !!!
 */

package com.unazed.LibraryManagement.model.gen;

public record DigitalBooks(
	String book_isbn,
	String book_url
) {}
