/* !!!
 * This file was auto-generated by schema-gen/main.py
 * Do not edit this file manually.
 * !!!
 */

package com.unazed.LibraryManagement.model.gen;

public enum UserStatus {
	ACTIVE,
	SUSPENDED,
	DELETED
}
