psql_java_type_map = {
    # numeric
    "integer": "int",
    "bigint": "long",
    "smallint": "short",
    "numeric": "java.math.BigDecimal",
    "decimal": "java.math.BigDecimal",
    "real": "float",
    "double precision": "double",
    "serial": "int",
    "bigserial": "long",

    # text
    "text": "String",
    "character varying": "String",
    "varchar": "String",
    "char": "String",
    "character": "String",
    "name": "String",

    # boolean
    "bool": "boolean",
    "boolean": "boolean",

    # date/time
    "date": "java.time.LocalDate",
    "time without time zone": "java.time.LocalTime",
    "time with time zone": "java.time.OffsetTime",
    "timestamp without time zone": "java.time.LocalDateTime",
    "timestamp with time zone": "java.time.OffsetDateTime",
    "interval": "org.postgresql.util.PGInterval",

    # binary
    "bytea": "byte[]",

    # uuid
    "uuid": "java.util.UUID",

    # json
    "json": "com.google.gson.JsonObject",
    "jsonb": "com.google.gson.JsonObject",

    # arrays
    "ARRAY": "java.sql.Array",

    # other
    "oid": "long",
    "void": "Void",
    "anyelement": "Object",
}

PREAMBLE = """\
/* !!!
 * This file was auto-generated by schema-gen
 * Do not edit this file manually.
 * !!!
 */\r\n\r\n"""


def get_table_schema(conn, schema: str, table_name: str)\
    -> list[tuple[str, str, str]]:
  with conn.cursor() as cur:
    cur.execute("""
        SELECT column_name, data_type, udt_name
        FROM information_schema.columns 
        WHERE table_schema = %s 
        AND table_name = %s;
      """, (schema, table_name))
    return cur.fetchall()


def get_sql_typtype(conn, schema: str, data_type: str) -> str:
  with conn.cursor() as cur:
    cur.execute("""
      SELECT typtype 
      FROM pg_type t
      JOIN pg_namespace n ON n.oid = t.typnamespace
      WHERE t.typname = %s
      AND n.nspname = %s
    """, (data_type, schema))
    row = cur.fetchone()
    assert row is not None, \
      f"!! no type found for {data_type!r} in schema {schema!r}"
    return row[0]


def get_enum_values(conn, data_type: str, schema: str) -> list[str]:
  with conn.cursor() as cur:
    cur.execute("""
      SELECT e.enumlabel
      FROM pg_enum e
      JOIN pg_type t ON t.oid = e.enumtypid
      JOIN pg_namespace n ON n.oid = t.typnamespace
      WHERE t.typname = %s
      AND n.nspname = %s
      ORDER BY e.enumsortorder
    """, (data_type, schema))
    return [row[0] for row in cur.fetchall()]


def snake_to_pascal(snake_str: str) -> str:
  components = snake_str.split('_')
  return ''.join(x.title() for x in components)


def snake_to_camel(snake_str: str) -> str:
  components = snake_str.split('_')
  return components[0] + ''.join(x.title() for x in components[1:])


def short_type_name(type_name: str) -> str:
  return type_name.split('.')[-1]


def get_sql_enum_info(conn, schema: str, data_type: str) -> dict:
  with conn.cursor() as cur:
    cur.execute("""
      SELECT t.typname, n.nspname
      FROM pg_type t
      JOIN pg_namespace n ON n.oid = t.typnamespace
      WHERE t.typname = %s
      AND n.nspname = %s
    """, (data_type, schema))
    row = cur.fetchone()
    assert row is not None, \
      f"!! no enum type found for {data_type!r} in schema {schema!r}"
    return {
      "name": snake_to_pascal(row[0]),
      "schema": row[1],
      "values": get_enum_values(conn, data_type, schema)
    }


def get_function_argspecs(conn, schema: str) -> dict:
  with conn.cursor() as cur:
    cur.execute("""
      SELECT 
        p.proname AS function_name,
        pg_get_function_arguments(p.oid) AS arguments,
        pg_get_function_result(p.oid) AS return_type
      FROM pg_proc p
      JOIN pg_namespace n ON n.oid = p.pronamespace
      WHERE n.nspname = %s
    """, (schema,))
    argspec = {}
    for func_name, func_args, func_rettype in cur.fetchall():
      argspec[func_name] = {
        "args": [arg.split(maxsplit=1) for arg in func_args.split(", ")],
        "ret": func_rettype
      }
    return argspec


def get_composite_fields(conn, schema: str, type_name: str) \
    -> list[tuple[str, str, str]]:
  with conn.cursor() as cur:
    cur.execute("""
      SELECT a.attname, t.typname, t.typtype
      FROM pg_class c
      JOIN pg_attribute a ON a.attrelid = c.oid
      JOIN pg_type t ON t.oid = a.atttypid
      JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE c.relname = %s
      AND n.nspname = %s
      AND c.relkind = 'c'
      AND a.attnum > 0
      AND NOT a.attisdropped
      ORDER BY a.attnum
    """, (type_name, schema))
    return cur.fetchall()